treemap-beta
"frontends/mindmap"
    "dialogs"
        "class-dialog.js": 94
        "compiler-dialog.js": 56
        "conflict-dialog.js": 12
    "shared"
        "classes.mjs": 50
        "documents.mjs": 40
        "html.js": 5
    "shell"
        "api.js": 13
        "dialogs.js": 17
        "registry.js": 17
        "router.js": 70
        "shell.js": 54
        "skin.js": 32
        "use-before-unload.js": 13
    "source"
        "batch.mjs": 20
        "documents.js": 106
        "draft.js": 39
        "draft.mjs": 73
        "graph.mjs": 136
        "history.mjs": 41
        "models.js": 40
        "projections.js": 29
        "projections.mjs": 59
        "source.js": 28
    "views"
        "documents"
            "flow"
                "flow-view.js": 136
                "projection.mjs": 73
            "map"
                "connect-dialog.js": 19
                "document-dialog.js": 82
                "document-node.js": 27
                "map-view.js": 153
                "projection.mjs": 50
                "quick-create-dialog.js": 32
                "sidebar.js": 11
                "statusbar.js": 5
                "toolbar.js": 10
        "draft"
            "tree"
                "tree-view.js": 92
        "models"
            "diagram"
                "diagram-view.js": 149
                "projection-editor.js": 79
                "projection.mjs": 143
    "app.js": 28
