import type { HumBodyModel } from './types';
import { generatedHumAstFiles, generatedHumAstForms } from './generated-hum-ast';

export const humBodyModel: HumBodyModel = {
  astFiles: generatedHumAstFiles,
  astForms: generatedHumAstForms,
  organs: [
    {
      id: 'organ-core',
      label: 'Core',
      packageName: ':hum.core',
      filePath: 'hum/agent/core.lisp',
      description: 'Coordinates objective intake, LLM prompting, action execution, and autopoietic closure.',
      position: { x: 360, y: 120 },
      colorToken: 'token-hum-core',
    },
    {
      id: 'organ-system',
      label: 'System',
      packageName: ':hum.system',
      filePath: 'hum/execution/system.lisp',
      description: 'Owns shell execution, confirmation, branching into git sessions, journaling, and raw turn dumping.',
      position: { x: 650, y: 120 },
      colorToken: 'token-hum-system',
    },
    {
      id: 'organ-tools',
      label: 'Tools',
      packageName: ':hum.tools',
      filePath: 'hum/execution/tools.lisp',
      description: 'Embodied capabilities registry; concrete tools are functional body parts, not external widgets.',
      position: { x: 930, y: 120 },
      colorToken: 'token-hum-tools',
    },
    {
      id: 'organ-energy',
      label: 'Energy',
      packageName: ':hum.energy',
      filePath: 'hum/energy/core.lisp',
      description: 'Measures entropy and computes systemic energy to feed the main reasoning loop.',
      position: { x: 1080, y: 350 },
      colorToken: 'token-hum-energy',
    },
    {
      id: 'organ-context',
      label: 'Context',
      packageName: ':hum.context',
      filePath: 'hum/agent/context.lisp',
      description: 'Persists distilled context between turns.',
      position: { x: 300, y: 560 },
      colorToken: 'token-hum-context',
    },
    {
      id: 'organ-thoughts',
      label: 'Thoughts',
      packageName: ':hum.thoughts',
      filePath: 'hum/agent/thoughts.lisp',
      description: 'Accumulates chain-of-thought fragments and writes them to disk.',
      position: { x: 540, y: 560 },
      colorToken: 'token-hum-thoughts',
    },
    {
      id: 'organ-knowledge',
      label: 'Knowledge',
      packageName: ':hum.knowledge',
      filePath: 'hum/agent/knowledge.lisp',
      description: 'Stores domains and explicit knowledge instances for later retrieval and closure.',
      position: { x: 780, y: 560 },
      colorToken: 'token-hum-knowledge',
    },
    {
      id: 'organ-stats',
      label: 'Stats',
      packageName: ':hum.stats',
      filePath: 'hum/energy/stats.lisp',
      description: 'Tracks token load and serializes it into the body state.',
      position: { x: 1020, y: 560 },
      colorToken: 'token-hum-stats',
    },
  ],
  capabilities: [
    {
      id: 'cap-bootstrap',
      organId: 'organ-core',
      label: 'bootstrap',
      functionName: 'bootstrap',
      filePath: 'hum/agent/core.lisp',
      description: 'Loads persisted state and starts a new session branch.',
      position: { x: 250, y: 240 },
      role: 'boot',
    },
    {
      id: 'cap-consulta-llm',
      organId: 'organ-core',
      label: 'consulta-llm',
      functionName: 'consulta-llm',
      filePath: 'hum/agent/core.lisp',
      description: 'Builds the prompt, asks the external LLM, and extracts a `(think ...)` shape.',
      position: { x: 420, y: 240 },
      role: 'reasoning',
    },
    {
      id: 'cap-ejecutar-accion',
      organId: 'organ-core',
      label: 'ejecutar-accion',
      functionName: 'ejecutar-accion',
      filePath: 'hum/agent/core.lisp',
      description: 'Dispatches parsed actions toward tools, state changes, or termination.',
      position: { x: 350, y: 350 },
      role: 'execution',
    },
    {
      id: 'cap-loop-autopoietico',
      organId: 'organ-core',
      label: 'loop-autopoietico',
      functionName: 'loop-autopoyetico',
      filePath: 'hum/agent/core.lisp',
      description: 'Runs post-task consolidation and lowers system energy through a commit ritual.',
      position: { x: 500, y: 350 },
      role: 'closure',
    },
    {
      id: 'cap-run-system-command',
      organId: 'organ-system',
      label: 'run-system-command',
      functionName: 'run-system-command',
      filePath: 'hum/execution/system.lisp',
      description: 'General shell/program execution interface.',
      position: { x: 610, y: 240 },
      role: 'io',
    },
    {
      id: 'cap-pedir-confirmacion',
      organId: 'organ-system',
      label: 'pedir-confirmacion',
      functionName: 'pedir-confirmacion',
      filePath: 'hum/execution/system.lisp',
      description: 'Safety gate between thought and action.',
      position: { x: 760, y: 240 },
      role: 'safety',
    },
    {
      id: 'cap-dump-raw-log',
      organId: 'organ-system',
      label: 'dump-raw-log',
      functionName: 'dump-raw-log',
      filePath: 'hum/execution/system.lisp',
      description: 'Writes raw turn payloads under autopoiesis session storage.',
      position: { x: 610, y: 350 },
      role: 'trace',
    },
    {
      id: 'cap-commit-state',
      organId: 'organ-system',
      label: 'commit-state',
      functionName: 'commit-state',
      filePath: 'hum/execution/system.lisp',
      description: 'Commits the embodied state back into git.',
      position: { x: 760, y: 350 },
      role: 'closure',
    },
    {
      id: 'tool-sldb-extraer',
      organId: 'organ-tools',
      label: 'sldb-extraer',
      functionName: 'sldb-extraer',
      filePath: 'hum/execution/tools.lisp',
      description: 'Reads structured markdown through sldb extraction.',
      position: { x: 900, y: 240 },
      role: 'knowledge ingress',
      kind: 'tool',
    },
    {
      id: 'tool-inspeccionar-self',
      organId: 'organ-tools',
      label: 'inspeccionar-self',
      functionName: 'inspeccionar-self',
      filePath: 'hum/execution/tools.lisp',
      description: 'Returns a compact symbolic self-inspection summary.',
      position: { x: 1060, y: 240 },
      role: 'self-inspection',
      kind: 'tool',
    },
    {
      id: 'tool-ejecuta-shell',
      organId: 'organ-tools',
      label: 'ejecuta-shell',
      functionName: 'ejecuta-shell',
      filePath: 'hum/execution/tools.lisp',
      description: 'Embodied shell actuator for external commands.',
      position: { x: 980, y: 350 },
      role: 'external action',
      kind: 'tool',
    },
    {
      id: 'cap-calculate-energy',
      organId: 'organ-energy',
      label: 'calculate-systemic-energy',
      functionName: 'calculate-systemic-energy',
      filePath: 'hum/energy/core.lisp',
      description: 'Computes systemic energy from entropy and token load.',
      position: { x: 1170, y: 430 },
      role: 'metabolism',
    },
    {
      id: 'cap-save-context',
      organId: 'organ-context',
      label: 'save-context',
      functionName: 'save-context',
      filePath: 'hum/agent/context.lisp',
      description: 'Serializes distilled context to `context.lisp`.',
      position: { x: 270, y: 675 },
      role: 'memory write',
    },
    {
      id: 'cap-save-thoughts',
      organId: 'organ-thoughts',
      label: 'save-thoughts',
      functionName: 'save-thoughts',
      filePath: 'hum/agent/thoughts.lisp',
      description: 'Writes the accumulated chain of thought.',
      position: { x: 515, y: 675 },
      role: 'memory write',
    },
    {
      id: 'cap-save-knowledge',
      organId: 'organ-knowledge',
      label: 'save-knowledge',
      functionName: 'save-knowledge',
      filePath: 'hum/agent/knowledge.lisp',
      description: 'Serializes explicit knowledge domains and instances.',
      position: { x: 780, y: 675 },
      role: 'knowledge persistence',
    },
    {
      id: 'cap-save-stats',
      organId: 'organ-stats',
      label: 'save-stats',
      functionName: 'save-stats',
      filePath: 'hum/energy/stats.lisp',
      description: 'Writes token usage and numeric state into `stats.lisp`.',
      position: { x: 1020, y: 675 },
      role: 'telemetry write',
    },
  ],
  artifacts: [
    {
      id: 'artifact-env',
      ownerId: 'organ-system',
      label: '.env',
      artifactPath: 'hum/.env',
      description: 'Provides `LLM_ENTRYPOINT` to the shell body.',
      position: { x: 640, y: 470 },
    },
    {
      id: 'artifact-context',
      ownerId: 'organ-context',
      label: 'context.lisp',
      artifactPath: 'hum/context.lisp',
      description: 'Persisted distilled context.',
      position: { x: 200, y: 790 },
    },
    {
      id: 'artifact-thoughts',
      ownerId: 'organ-thoughts',
      label: 'thoughts.lisp',
      artifactPath: 'hum/thoughts.lisp',
      description: 'Persisted thought chain.',
      position: { x: 430, y: 790 },
    },
    {
      id: 'artifact-journal',
      ownerId: 'organ-system',
      label: 'journal.lisp',
      artifactPath: 'hum/journal.lisp',
      description: 'Compact event journal with action/result pairs.',
      position: { x: 650, y: 790 },
    },
    {
      id: 'artifact-stats',
      ownerId: 'organ-stats',
      label: 'stats.lisp',
      artifactPath: 'hum/stats.lisp',
      description: 'Token accounting persisted by the body.',
      position: { x: 860, y: 790 },
    },
    {
      id: 'artifact-session-log',
      ownerId: 'organ-system',
      label: 'hum-sessions/',
      artifactPath: 'hum/desk/autopoiesis/hum-sessions/',
      description: 'Raw turn dumps for later autopoietic consolidation.',
      position: { x: 1085, y: 790 },
    },
  ],
  routines: [
    {
      id: 'task-execution',
      label: 'Task Execution',
      description: 'The main perceive-think-confirm-act-persist routine running through HUM.',
      steps: [
        { id: 'rt-bootstrap', label: 'Bootstrap', targetId: 'cap-bootstrap', description: 'Load persisted state and initialize a session branch.', status: 'critical' },
        { id: 'rt-energy', label: 'Measure Energy', targetId: 'cap-calculate-energy', description: 'Compute systemic energy before reasoning.', status: 'critical' },
        { id: 'rt-llm', label: 'Consult LLM', targetId: 'cap-consulta-llm', description: 'Build prompt and retrieve a `(think ...)` response.', status: 'critical' },
        { id: 'rt-confirm', label: 'Confirm Action', targetId: 'cap-pedir-confirmacion', description: 'Check safety and obtain user authorization unless YOLO.', status: 'critical' },
        { id: 'rt-execute', label: 'Execute Action', targetId: 'cap-ejecutar-accion', description: 'Dispatch tool call or completion action.', status: 'critical' },
        { id: 'rt-persist-context', label: 'Persist Context', targetId: 'cap-save-context', description: 'Update the distilled context.', status: 'expected' },
        { id: 'rt-persist-thoughts', label: 'Persist Thoughts', targetId: 'cap-save-thoughts', description: 'Write chain-of-thought state.', status: 'expected' },
        { id: 'rt-persist-stats', label: 'Persist Stats', targetId: 'cap-save-stats', description: 'Update token accounting.', status: 'expected' },
        { id: 'rt-log', label: 'Dump Raw Log', targetId: 'cap-dump-raw-log', description: 'Write raw turn data for phase-2 closure.', status: 'expected' },
        { id: 'rt-close', label: 'Autopoietic Closure', targetId: 'cap-loop-autopoietico', description: 'Run consolidation and commit state if the task is done.', status: 'optional' },
      ],
    },
    {
      id: 'autopoiesis',
      label: 'Autopoiesis',
      description: 'The closure ritual that commits state and lowers systemic energy.',
      steps: [
        { id: 'ap-energy-before', label: 'Sample Energy', targetId: 'cap-calculate-energy', description: 'Measure energy before closure.', status: 'critical' },
        { id: 'ap-commit', label: 'Commit State', targetId: 'cap-commit-state', description: 'Commit embodied state after consolidation.', status: 'critical' },
        { id: 'ap-energy-after', label: 'Measure After', targetId: 'cap-calculate-energy', description: 'Measure the resulting energy after closure.', status: 'expected' },
      ],
    },
    {
      id: 'tool-definition',
      label: 'Tool Definition',
      description: 'A body-changing routine that adds a new capability and persists it.',
      steps: [
        { id: 'td-define', label: 'Define Tool', targetId: 'organ-tools', description: 'Register a new embodied capability.', status: 'critical' },
        { id: 'td-persist', label: 'Persist Tool', targetId: 'tool-ejecuta-shell', description: 'Write tool code into the tools file.', status: 'expected' },
        { id: 'td-commit', label: 'Commit Tool State', targetId: 'cap-commit-state', description: 'Commit the changed body.', status: 'expected' },
      ],
    },
  ],
  traces: [
    {
      id: 'trace-inspection-loop',
      label: 'Inspection Loop',
      description: 'Observed run from `hum/journal.lisp`: HUM tries self-inspection twice and loops on an unknown action.',
      routineId: 'task-execution',
      events: [
        {
          id: 'te-goal',
          label: 'Receive Goal',
          targetId: 'cap-bootstrap',
          description: 'Objective is self-inspection with empty distilled context.',
          outcome: 'done',
          mirrorsStepId: 'rt-bootstrap',
          energyDelta: 0,
        },
        {
          id: 'te-energy',
          label: 'Energy 570.0',
          targetId: 'cap-calculate-energy',
          description: 'Trace records systemic energy at 570.0 before action selection.',
          outcome: 'done',
          mirrorsStepId: 'rt-energy',
          energyDelta: 570,
        },
        {
          id: 'te-inspect-1',
          label: 'Try INSPECCIONAR-SELF',
          targetId: 'tool-inspeccionar-self',
          description: 'The body attempts self-inspection as the chosen action.',
          outcome: 'failed',
          mirrorsStepId: 'rt-execute',
          notes: 'Journal result: Accion desconocida: INSPECCIONAR-SELF',
        },
        {
          id: 'te-loop',
          label: 'Retry Same Action',
          targetId: 'tool-inspeccionar-self',
          description: 'Second thought acknowledges the failure but proposes the same unavailable action again.',
          outcome: 'looping',
          mirrorsStepId: 'rt-execute',
          notes: 'This is a trace-level divergence from the canonical routine.',
        },
        {
          id: 'te-journal',
          label: 'Journal Result',
          targetId: 'artifact-journal',
          description: 'The available artifact confirms the repeated unknown action.',
          outcome: 'done',
          notes: 'Backed by `hum/journal.lisp`.',
        },
      ],
    },
  ],
};
