import {html} from '../../../shared/html.js';

// Owns everything the previous topbar/toolbar split for the map view: the
// mobile sidebar toggle and the focus breadcrumb moved here from the shell
// topbar (Phase C) alongside the original toolbar controls.
export function Toolbar({ready,saving,dirty,onAdd,onUndo,onRedo,canUndo,canRedo,onFit,onOverview,onSort,
  showRelations,setShowRelations,onExport,onImport,query,setQuery,onSearch,
  focusId,focusTitle,onExitFocus,sidebarOpen,setSidebarOpen}) {
  return html`<div className="toolbar" role="toolbar" aria-label="Herramientas del mapa"><button className="mobile-menu icon-button" aria-label="Mostrar clases" onClick=${()=>setSidebarOpen(!sidebarOpen)}>☰</button><button className="add-button" disabled=${!ready||saving} onClick=${onAdd}>＋ Documento</button><span className="separator"></span><button onClick=${onUndo} disabled=${!canUndo||saving} aria-label="Deshacer" title="Deshacer (Ctrl+Z)">↶</button><button onClick=${onRedo} disabled=${!canRedo||saving} aria-label="Rehacer">↷</button><span className="separator"></span><button onClick=${onFit} disabled=${!ready}>⛶ Lectura</button><button onClick=${onOverview} disabled=${!ready}>Ver todo</button><button onClick=${onSort} disabled=${!ready||saving}>Ordenar</button><label className="relations-toggle"><input type="checkbox" checked=${showRelations} onChange=${e=>setShowRelations(e.target.checked)}/> Referencias</label><button onClick=${onExport} disabled=${!ready||saving}>Exportar</button><button onClick=${onImport} disabled=${!ready||saving||dirty} title=${dirty?'Guarda los cambios pendientes antes de importar':'Importar un mapa JSON'}>Importar JSON</button>${focusId?html`<div className="focus-breadcrumb"><button onClick=${onExitFocus}>Mapa completo</button><span>›</span><strong>${focusTitle}</strong><button className="focus-exit" onClick=${onExitFocus}>Salir del foco</button></div>`:''}<form className="search" onSubmit=${e=>{e.preventDefault();onSearch();}}><input aria-label="Buscar documento" placeholder="Buscar documento…" value=${query} onInput=${e=>setQuery(e.target.value)}/><button aria-label="Buscar" type="submit">⌕</button></form></div>`;
}
